# Generated by Django 5.1.1 on 2025-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LX', 'luxury'), ('SD', 'sedan'), ('HC', 'hatchback '), ('CM', 'compact'), ('SV', 'suv')], max_length=2),
        ),
    ]
