# Generated by Django 5.1.1 on 2025-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_product_model_product_rent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='A', max_length=1),
        ),
    ]
