# Generated by Django 5.1.1 on 2025-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_product_fuel_type_product_seats_product_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='Petrol', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='Automatic', max_length=1),
        ),
    ]
