# Generated by Django 5.1.1 on 2025-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_product_fuel_type_alter_product_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(max_length=20),
        ),
    ]
