# Generated by Django 5.1.1 on 2025-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_product_fuel_type_alter_product_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(default=1000),
        ),
    ]
