# Generated by Django 5.1.1 on 2025-02-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_booking_booking_date_payment_booking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
    ]
